name: Run CBOM Analysis with Custom Setup

on:
  push:
  pull_request:

jobs:
  cbom-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize Submodules
        run: git submodule update --init --recursive

      - name: Run CBOM Analysis (cbae tool)
        uses: Namokar100/cbae-action@v1.0.8
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commands-to-install-build-tools: |
            python -m pip install --upgrade pip
            pip install sphinx pipenv  # adjust as needed
          build-command: |
            autoreconf -fi && ./configure && make 